---
- name: Reconfiguration du service Redis pour accès distant
  hosts: fedoracli
  become: true

  tasks:
    - name: Désactivation du service firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Reconfiguration directive bind dans /etc/redis/redis.conf
      ansible.builtin.lineinfile:
        dest: "{{ redis_config_filename }}"
        regex: ^bind 0.0.0.0
        line: bind 192.168.56.246
      register: result_bind

    - name: Désactivation du mode protected
      ansible.builtin.lineinfile:
        dest: "{{ redis_config_filename }}"
        regex: ^protected-mode on
        line: protected-mode no
      register: result_protected

    - name: Redémarrage du service redis
      ansible.builtin.service:
        name: redis
        state: restarted
      when:
        - result_bind.changed == true or result_protected.changed == true
