---
- name: La clause loop
  hosts: debycli

  tasks:
    - name: Liste de couleurs
      ansible.builtin.debug:
        msg: "Couleur n°{{ nb + 1 }}: {{ couleur }}"
      loop:
        - Marron
        - Violette
        - Rose
      loop_control:
        loop_var: couleur
        index_var: nb

    - name: Liste des interfaces
      ansible.builtin.debug:
        msg: "Interface: {{ iface }}"
      loop: "{{ ansible_interfaces | sort }}"
      loop_control:
        loop_var: iface
      when: iface != 'lo'

    - name: Simulacre de block...loop
      ansible.builtin.include_tasks:
        file: tasks.yml
      loop:
        - iteration_1
        - iteration_2

    - name: Inclusion logins.yml
      ansible.builtin.include_vars:
        file: logins.yml
      tags: login

    - name: Boucles imbriquées
      ansible.builtin.debug:
        msg: "{{ item.0.login }} {{ item.1 }}"
      loop: "{{ logins | subelements('groups') }}"
      tags: login
      
