---
# tasks file for roles.d/php-fpm

- name: Installation/configuration PHP-FPM sur groupe php
  when: inventory_hostname in groups.php
  block:
  - name: Désactivation/arrêt du service firewalld
    ansible.builtin.systemd_service:
      name: firewalld
      state: stopped
      enabled: false

  - name: Installation du serveur php-fpm
    ansible.builtin.package:
      name: "{{ lookup('vars','php_fpm_package_name_'+ansible_os_family|lower) }}"

  - name: Configuration du service php-fpm
    ansible.builtin.systemd_service:
      name: "{{ lookup('vars','php_fpm_service_name_'+ansible_os_family|lower) }}"
      state: started
      enabled: true

  - name: Directive listen
    ansible.builtin.lineinfile:
      regex: ^listen = /run/php-fpm/www.sock
      line: "listen = {{ ansible_all_ipv4_addresses | regex_search('192.168.[.0-9]+') }}:9000"
      dest: /etc/php-fpm.d/www.conf
    notify: restart_php

  - name: Directive listen.allowed_clients
    ansible.builtin.lineinfile:
      backrefs: true
      state: present
      regex: ^(listen\.allowed_clients.*)$
      line: ;\1
      dest: /etc/php-fpm.d/www.conf
    notify: restart_php
